### ISSUE TITLE
Firmware missing

### ISSUE THREAD

**Issue by mikecardwell** [Xeddius/OfficejetPro86xx-Downgrade#2]
I don't suppose you still have a copy of the firmwares? They don't seem to be available anymore... Specifically for the 8620?

**Comment by l3nticular** [comment]
Same here. I would be interested to make sure I have this in my pocket.

**Comment by Xeddius** [comment]
Sorry for the late response, it would seem they've removed the firmware from their servers entirely now. I'll see if I can find my backup copies tomorrow when I have access to my external drives.
